### PR TITLE
Removed low-level custom drawing in the canvas

### PR DESCRIPTION
**Pull request by tinchodias**
- Just add and remove children.
- For card's back, show a Form that was already at class-side (instead of the cross).

### CODE REVIEW

**Comment by tinchodias** [comment]
It looks like this, what do you think? 
Screenshot 2023-04-20 at 21 02 44

I imagine this embedded Form as method was not as good for the tutorial and was replaced by the cross. By the low-level code to draw front and back side of the cards is not necessary, anyway. Better to use standard geometries.

**Comment by StephanEggermont** [comment]
Hmm. The whole idea is to show drawing primitives being used. They might have to be updated later with a different backend, but removing them? Or is there a different example going into details about them?

**Comment by syrel** [comment]
In early 2017, when the Memory Game tutorial was written, it was supposed to address the concern that in Bloc it should be possible to just subclass a `BlElement` and render directly on the canvas, like it was commonly done in Morphic at the time.

In 2018, [`MgComposedCardElement`](https://github.com/pharo-graphics/Tutorials/blob/3cbc8758f7f71ab0eab9bc134aa9e3f18aa0b0bb/src/Bloc-MemoryGame/MgComposedCardElement.class.st) version of the `CardElement` was added that showcased how to implement the same card but now using element composition instead of raw rendering.

Both cards looked identical, including crossing lines, which was the whole point to emphasise how powerful the composition actually can be.
🤷‍♂️

**Comment by Ducasse** [comment]
Tx martin

**Comment by tinchodias** [comment]
I'm back after a couple of weeks. Well, I take note of the feedback and will bring Boids to this repo with custom drawing code.

**Pull request merged**
